name:           Galileo Correspondence Project
destination:    ./_site
plugins_dir:        ./_plugins
layouts_dir:        ./_layouts

highlighter:    pygments

permalink:      :year/:month/:day/:title
markdown:       kramdown
markdown_ext:   md

url:        http://galileo.stanford.edu/
