name:           Galileo Correspondence Project
destination:    ./_site
plugins:        ./_plugins
layouts:        ./_layouts

highlighter:    pygments

permalink:      :year/:month/:day/:title
markdown:       kramdown
markdown_ext:   md

baseurl:        http://galileo.stanford.edu/